### ISSUE TITLE
[Windows] Black flicker on some GPUs/devices when using H/W rendering

### ISSUE THREAD

**Issue by alexmercerind** [alexmercerind/media_kit#10]
Feedback needed.

**Comment by alexmercerind** [comment]
Personally speaking, I have entry-level AMD Ryzen 3 2200U processor with integrated Raden Vega 3 Mobile Graphics.

I don't see any flicker at all. Only 4K 60 FPS videos seem to be flickering, but even 4K 30 FPS are playing fine.
Please comment your experience.

**Comment by alexmercerind** [comment]
No objections so far. Closing.
No problems on other GPUs/devices I tested either.

**Comment by Quackdoc** [comment]
I was able to replicate it on my rx580, it seems like it might be random 
[info.txt](https://github.com/alexmercerind/media_kit/files/10302894/info.txt)

**Comment by alexmercerind** [comment]
> I was able to replicate it on my rx580, it seems like it might be random
> [info.txt](https://github.com/alexmercerind/media_kit/files/10302894/info.txt)

Thanks!
- You attempted to play the videos present on the right-side, right?
- From the logging file, are you running on higher than 60 FPS?

**Comment by Quackdoc** [comment]
Im running 60fps on my monitor, 

I did play the videos on the right side of the screen and they rarely caused flickering to occur. however downloading a longer video from youtube and loading that up did consistently cause the flickering to occur, I think the higher the resolution the more it occurs. 

I did try disabling hwdec, but that didn't seem to have any bearing on the flickering at all. 

I did also add file-log to the mpv string, and the logs it pumped out didn't seem to be correlate to the flashing at all.

I did try to test on linux, but the same program you have doesn't seem to compile, so I replaced vlc_dart with mediakit in a private application i have accsess to, but sadly it doesn't seem like embedding code is wired up, though it does create an mpv context just fine at least.

**Comment by alexmercerind** [comment]
Thanks!

> I did play the videos on the right side of the screen and they rarely caused flickering to occur. however downloading a longer video from youtube and loading that up did consistently cause the flickering to occur, I think the higher the resolution the more it occurs.

On my device, only 4K 60 FPS videos flicker black.
I don't have much idea either. However, it is really important to resolve this issue.

> I did try to test on linux, but the same program you have doesn't seem to compile, so I replaced dart_vlc with media_kit in a private application I have access to, but sadly it doesn't seem like embedding code is wired up, though it does create an mpv context just fine at least.

Yeah, Linux implementation is not done yet.
Currently focusing on Windows.

**Comment by Quackdoc** [comment]
my first thought is GPU load, so I spun up a game in windows mode, and alt+tabbed between the two of them and the flashing was absolutely exacerbated, it was a significant change when it was running int he background, which since windows default behavior is to prioritize foreground apps for gpu, this makes a lot of sense

to further test it, I downloaded DXVK, a popular directX->VK wrapper, https://github.com/doitsujin/dxvk/releases/tag/v2.0

and I have not been able to get the flashing since. while I do have a couple theories as to why this is, my first thought is maybe this is a bug in flutters rendering engine. sadly im not too familar with flutter profiling so this is as far as this goes

**Comment by alexmercerind** [comment]
What's the FPS & resolution combination that's flickering for you?

**Comment by alexmercerind** [comment]
The black flicker are frame drops likely. When running mpv directly, I get quite a lot of frame drops with default setting. If I use `d3d11va` or `dxva2`, frame drops are substantially less. `dxva2-copy` is used by this setup.

**Comment by Quackdoc** [comment]
in isolation, 1920p30 video is typically fine, however if im watching a second video in another MPV instance with some moderate gpu settings, that will cause flickering consistently 

4k30 really starts flickering badly, however when I have a game running, so much as a 720p30 can cause a good chunk of flickering.

Im not sure it is MPV dropping frames, at least not in isolation, since running 4k30 while a game is in the foreground causes the video to become stutery as one would expect when it doesn't have enough gpu power (this happens with all video players, not just MPV) however it does not become flickery at all. 

using DXVK_HUD=1 we can actually see that flutter is rendering less then framerate when tabbed out. so the preformance hit is certainly effecting playback.

![image](https://user-images.githubusercontent.com/74831516/209583825-372328c2-24a3-4e97-a381-05b17918e3b8.png)

**Comment by alexmercerind** [comment]
Hi @Quackdoc,

I've made a fix & I'm really-really hopeful about this.

In my experience, this flickering was not due to dropping frames but due to "excessive frames" & this was mainly due to my implementation. Now, I'm not seeing any flickering or tearing at all, even with 4K 60 FPS.

Flickering will never show up. If any substantial load stays on the computer (I mean 4K video playback is not that "easy" as it may look for GPU), then frames will be dropped instead (how it should be). I opened a game in windowed mode & I can certainly see little lag in video, but no flickering. Also, I think your issue was likely due to dual-monitor setup, now I manually pick the refresh rate & play video according to it. Similar issues exist for mpv too: https://github.com/mpv-player/mpv/issues/9686.

In general usage, there is no flickering or dropped frames at all. Decent experience.

<hr>

I'm attaching the updated release-mode executable to test. Please confirm the fix.

[media_kit_test.7z](https://drive.google.com/file/d/1-Ce-iiAG18McJ_o6JG43i2tHyrNzOLMI/view?usp=sharing)

Thanks!

**Comment by alexmercerind** [comment]
Rest, Windows itself schedules the running applications so the thing may perform worse in background. So, a good idea can be to skip the rendering loop when window is minimized or some another app is maximized. Google Chrome also does the same.

**Comment by Quackdoc** [comment]
Just tested it, and sadly it is still exhibiting similar issues. tomorrow I will have access to an Intel I3 6100 with integrated graphics for testing, but in the meantime

I outright disabled the second GPU in the PC (DG2 so that certainly could have contributed) and am now running a single 60hz monitor, and the issue is still persisting. I also tried a fresh clone and building myself and it too was having the issues

**Comment by alexmercerind** [comment]
That's sad. I did add some additional logging (likely you built with it).
The first number should always be lesser than the later. Otherwise frames will be dropped (to avoid flicker).
For me, this fixed it. Are you seeing something similar?

![Screenshot 2022-12-27 151653](https://user-images.githubusercontent.com/28951144/209655594-e59e35f8-7437-4578-a0a6-16d2fae0a0a1.jpg)

**Comment by Quackdoc** [comment]
This is the output of doing `flutter run` even no dropped frame messages, and didnt see a single time when it exceeded the second number

![image](https://user-images.githubusercontent.com/74831516/209658197-4e5c0689-cad1-49da-82fc-f967edb3eeb0.png)

**Comment by Quackdoc** [comment]
sorry for the delay, I did test on an i3 6100 with igpu machine and the problem DOES occur there too, so it is not isolated to AMD

**Comment by alexmercerind** [comment]
For 60 FPS videos or the videos on the right? We should first address the smaller issues.

**Comment by Quackdoc** [comment]
I think I found the issue may need to change how `d3d11_texture2D_desc.Format` gets handled. for instance I change 

```
d3d11_texture2D_desc.Format = DXGI_FORMAT_B8G8R8A8_UNORM
to
d3d11_texture2D_desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM
```

OGL/GLES is notoriously finicky, pixel formats in specific are a pain point, I think it might have been doing a pixel format conversion? im not entirely sure exactly what is being used here 

but this has solved my issue, even when overriding 
`#define HW_RENDERING_REFRESH_RATE_SUBTRAHEND 0`

I can try to confirm on the i3 6100 system later. however im pretty sure this should work for all windows systems, since as far as I know, the only real consumer of `GL_BGRA8_EXT` which is `B8R8G8A8_UNORM` is apple

you can see the mappings here 
https://chromium.googlesource.com/angle/angle/+/34cc136a689711ee7f64f90b2de9b07cfb9a9f17/src/libANGLE/renderer/d3d/d3d11/formatutils11.cpp

**Comment by alexmercerind** [comment]
> I think I found the issue may need to change how `d3d11_texture2D_desc.Format` gets handled. for instance I change
> 
> ```
> d3d11_texture2D_desc.Format = DXGI_FORMAT_B8G8R8A8_UNORM
> to
> d3d11_texture2D_desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM
> ```
> 
> OGL/GLES is notoriously finicky, pixel formats in specific are a pain point, I think it might have been doing a pixel format conversion? im not entirely sure exactly what is being used here
> 
> but this has solved my issue, even when overriding `#define HW_RENDERING_REFRESH_RATE_SUBTRAHEND 0`


Hi @Quackdoc,

I think it's not the fix however. As far as I can tell, this will cause hardware (Direct3D + ANGLE) initialization to fail.
And thus, it will fall back to the software renderer (bad for CPU & battery life), I've written a fallback (see `video_output.cc`).

```
media_kit: ANGLESurfaceManager: Direct3D Feature Level: 11_1
media_kit: ANGLESurfaceManager: Failure: eglCreatePbufferFromClientBuffer
media_kit: VideoOutput: Using S/W rendering.
```

You must see "Using H/W rendering." in your logs.

**Comment by alexmercerind** [comment]
However, please feel free to change code & find the perfect configuration for your machine.
I'll be genuinely happy to accept the contributions. I'm not much into Direct3D/OpenGL either.

I used this for ANGLE interop: https://github.com/Microsoft/angle/wiki/Interop-with-other-DirectX-code.
I kept the same Direct3D texture creation parameters.

**Comment by alexmercerind** [comment]
Hi @Quackdoc, I pushed one more attempt to fix the issue. I will love to hear back. Thanks again!

Please `git pull` or fresh `git clone` again. You may experiment with these three lines too:

https://github.com/alexmercerind/media_kit/blob/d307ba6d286855353133e18e4394637049d73bb9/media_kit_core_video/windows/video_output.cc#L181-L183

**Comment by alexmercerind** [comment]
Do not enable both `glFlush` and `glFinish` at once. I have a feeling `glFinish` should work.

**Comment by Quackdoc** [comment]
unfortunately, I now just crash, this is after I did a clean git clone again

**Comment by alexmercerind** [comment]
@Quackdoc,

Thanks! The other guy's flickering has been fixed with latest commit. I compiled a new release build. Try it out:

[flutter-render-thread-mpv-notify-gl-finish.7z](https://drive.google.com/file/d/1uOvlOUh93Cl96KhYhkAN6anEbyXWrsOe/view?usp=sharing)

I'm confused by the fact that he is crashing when he compiles locally.

**Comment by Quackdoc** [comment]
I'm not flickering under normal use which is a massive improvement for sure, but when I start up a moderate game it does cause very occasional flickering still

and when I started up a game that really hit the gpu, or when I start MSI kombustor (gpu stress test) it flickers really badly.

and I did test for the sake of testing, this build actually seems to have broken DXVK, which has me a bit worried, since intel might be heading that way for their DGPUs (they already do it for DX9 and DX10). (this is not an issue right now though just a potential one in the future. since intel is still using native DX11 as far as I am aware).

at the very least, it's good enough for me to work with, but while I might just have a special system, it might be a good idea to keep in mind that the issue might not be solved, but rather I think that whatever you have done has increased performance enough that it has pushed and hidden the issue. which in either case is a very good thing anyways.

but like I said, I do find the DXVK issue mildly concerning

**Comment by sudongg** [comment]
I downloaded the media_kit_test.exe file you provided and the flickering is very noticeable.
Try adding mpv_set_option_string(mpv,"video-timing-offset", "0");

**Comment by alexmercerind** [comment]
@sudongg, I think you left a comment here, please try the latest .exe, it will work well.

[flutter-render-thread-mpv-notify-gl-finish.7z](https://drive.google.com/file/d/1uOvlOUh93Cl96KhYhkAN6anEbyXWrsOe/view?usp=sharing)

<hr>

**Comment by sudongg** [comment]
I've downloaded a new exe, tested it, and it doesn't flicker anymore.

**Comment by alexmercerind** [comment]
@Quackdoc,

As long as this package is able to play 4K 60 FPS performantly in a H/W accelerated way (_which it clearly is, after latest commit_), it is good to go. There's **no flickering anymore** on my machine, neither my colleague's machines. In my personal tests, this already performs better than video playback in Chromium-based browsers (in terms of CPU/GPU usage).

Even 4K 60 FPS is sort of a "benchmark" here. In general usage I don't think one is ever going higher (unless one is developing a media player specifically). I'm not here to test the limits, but I'm pretty sure running a stress test software or a game alongside will definitely cause frame-drops in mpv (or any other media player) too.

The flickering issue only existed because I was rendering video output in a detached-background thread, which was clearly not synced. Now, all the render methods from libmpv are called on Flutter's rendering thread (as it should be). Rest, Direct3D, ANGLE & OpenGL heavily depend upon hardware, driver, operating system etc. So, it can't be clearly said if it's a fault in my code now that everything is working fine on most devices.

Any improvements can/will certainly be made in future, for now this is working great (_and as intended_) !

<hr>

My 250$ machine with budget AMD Ryzen 3 2200U & integrated Radeon Vega 3 Mobile Graphics has been working fine with all this time, except 4K 60 FPS (1080p 60FPS & 4K 30 FPS were still working great). After recent fixes, everything is addressed for me & other people I asked to.

<hr>

Another reasoning here is that mpv comes with a number of `hwdec`s, you are fine to choose the perfect configuration for your hardware & share as required. However, numer of supported `hwdec`s is going to be quite limited since we are forcing OpenGL usage through ANGLE.

**Comment by alexmercerind** [comment]
Also... I will be glad to hear back confirmation for the fix to recent crash you experienced (_and the flicker_).

**Comment by Quackdoc** [comment]
I did a git clone, and compiled it again, I am still getting flickering when running a game. 1080p30 will flicker maybe once a minute not unbearable, but still not good, 4k30 is still unwatchable as it flickers about once every 10 seconds or more. as it stands this can happen with any relatively moderate 3d workload.

I tested the new build on an i3 6100 as well which can't even do 4k30 without flickering when the only other thing running is a notepad and it is in focus. the igpu can typically do 4k60 with zero issues unless I had a great amount of shaders to MPV. I plan on testing to see if my laptop can even run it, (I normally have it running linux, so I need to get a windows install medium before I can test). 

These aren't frame drops though, I can run MPV with "always on top" and "transparency" while playing a game and render a video at 2x fps untimed. the video in the media_kit is rendering at real time. Even forcing it to slow to a halt by using 4k60 while gaming shows that while the video crawls, the black frames don't increase any more then 4k30.

the problem does seem to be solved so long as the app is in focus at the very least. on that PC but that's not usable for me personally so Ill keep looking into the issue at least. 

I don't think it's a fault in your code, I don't think it ever was since DXVK has zero issues with black frames at all no matter how hard the system was running, it didn't produce a single black frame at all, suggesting that the issue is somewhere within the rendering pipeline itself, and not the copy from angle to DirectX, as DXVK only translated DirectX calls into vulkan. 

I think it has more to do with how angle and DX interact with each other. 

I did try to look more into the pixel format issues with angle, I'm still confused as to why they won't work, however at this point instead of messing around with angle, I plan on adding `GL_BGRA8_EXT` support to MPV to see if that can help with the flickering issues. However getting libmpv to compile in the way that flutter would use it has proven to be quite a pain...

I plan on basing the work around commit #5aa9f59a841db383181cdf3e5306d644a4b999b7 for now as the next commit after that broke DXVK which might be able to help me debug the issue. and at the very least, since DXVK totally solves the issue, I can at least use that to work around it not being focused. in the mean time.

though to be blunt, I don't think a **proper** solution will be possibly until flutter migrates to impeller, since IIRC they are working on a vulkan backend for it on windows anyways. which has a lot better interop with gles. though, I guess if vulkan/native GL does solve the issue. I could just run the app in WSL2 if it comes to it.

**Comment by alexmercerind** [comment]
The other guy has reported that his video playback starts to flicker if he re-sizes the video.
Maybe that has something to do with your game-play in another window.

**Comment by alexmercerind** [comment]
> I don't think a proper solution will be possibly until flutter migrates to impeller, since IIRC they are working on a Vulkan backend for it on windows anyways. which has a lot better interop with glES.

Agreed. However, current **whole** public texture API in Flutter Windows is Direct X based.
I don't think Impeller (at-least for Windows, Linux or macOS) is coming any-time soon (or maybe ever).
ANGLE is heavily used by Google's own projects, one being Chromium itself & so is Skia.
So, I'm kinda confident that this situation is here to stay.

<hr>

On the other hand, for non-Windows platforms, I think we have a good opportunity since public texture API for other platforms is OpenGL based, which means no involvement of OpenGL ES standard / ANGLE interop etc. etc.
It should be more performant & more stable in general. So, Linux is a good goal for now.

<hr>

Besides all of this, this implementation has been working flawlessly without any flickers at all on my machine.
I'm more confused than ever. Let's see...

**Comment by Quackdoc** [comment]
firstly looking into the flickering, Im not sure exactly what is causing it since im not familiar with windows dev tools. however looking at the --trace-skia output, not every time, but usually when there is a black frame, there is a spike in gpu-raster time. 

So, I've been playing around a bit, for now at least for me, it seems like disabling 3d acceleration, but using d3d11va-copy to accelerate video decoding seems to be a "good" route, when under gpu limited scenarios. I think the majority of people won't need this, so maybe simply exposing S/W render with video accel as an option so the apps can set it themselves, this might be a  debug good option?

and as a side note for the sake of having more info in the thread, it might be possible in the *future* to use libmpv with a vulkan backend, which could very well be the better solution. 

https://github.com/mpv-player/mpv/issues/10810

as for short term solutions, it might be viable to use `SetGPUThreadPriority()` when dealt with this would make it so putting the app in the background shouldn't go lower on priority preventing the flickering altogether unless an app with a higher priority comes along, which should be quite rare.


examples
d3d9
https://github.com/microsoft/Windows-classic-samples/blob/7cbd99ac1d2b4a0beffbaba29ea63d024ceff700/Samples/Win7Samples/multimedia/direct3d/direct3d9ex/BackgroundThread.cpp#L66

d3d11
https://github.com/obsproject/obs-studio/blob/e62759a3fa3d20366f80ddaa70fa58ca4f61a358/libobs-d3d11/d3d11-subsystem.cpp#L566

The **significant** issue is, im not sure if this needs to happen when the dxgi adapter is made, or if this would need to be done for flutter's skia engine itself

**Comment by sudongg** [comment]
@alexmercerind 
The latest exe doesn't flicker on me. But there still seems to be users flickering.

According to previous experience, setting `mpv_set_option_string(mpv,"video-timing-offset", "0")` can prevent flickering.

If SwapBuffer has been used, glFlush() or glFinish() does not need to be performed again. If SwapBuffer is not used, flickering may occur during scaling.

Setting SwapInterval to 1 can also avoid flickering. If it is set to 0, you need to synchronize manually, using D3DKMTWaitForVerticalBlankEvent or DwmFlush (Windows platform).

In my mpv+opengl project, as long as I set video-timing-offset to 0, SwapInterval to 1, and use SwapBuffer, there will be no flickering.

**Comment by Quackdoc** [comment]
do you mean `opengl-swapinterval`?

I added 

```
mpv_set_option_string(handle_,"video-timing-offset", "0");
mpv_set_option_string(handle_,"opengl-swapinterval", "1");
```

and its flickering real badly

**Comment by sudongg** [comment]
@Quackdoc 
Please make sure you downloaded the latest exe, the latest exe has no flicker in my place.
If you try to set video-timing-offset = 0 on mpv, and use SwapInterval = 1 on the opengl side, and use SwapBuffer, it still flickers, it may be a problem on the flutter side.

**Comment by alexmercerind** [comment]
Personally speaking, I have no flickers even without `glFinish` (it fixed once I moved rendering to Flutter's render thread).
I think same will work for you @sudongg (no `glFinish`).

Since, I can't reproduce this, it's like shooting in the dark for me. I'm just adding/removing things & asking y'all to test out.
Ideally, there should be no `glFinish` for optimal performance, however nothing matters more than correct functionality.

<hr>

Thus, please try out compiling the project on your machine.
Edit, add or modify the configuration / function-calls from OpenGL ES or ANGLE API or Direct3D etc. 
I'm pretty sure you'll hit a sweet spot.

Few other clues I'd like to drop:

1. As far as my knowledge goes, we are not using `--vo=opengl` from libmpv so things like `opengl-swapinterval` won't make any difference.
2. As @sudongg said, `D3DKMTWaitForVerticalBlankEvent` or `DwmFlush` can actually make difference, these calls (as far as my knowedge goes should be placed where `glFinish` is currently). Maybe `DwmFlush` is the `glFinish` of DirectX, which will make more sense here & can likely fix everything (for now). 

https://github.com/alexmercerind/media_kit/blob/083f128876f4a156a61c70a73c93558b808e3c1f/media_kit_core_video/windows/video_output.cc#L157

3. As @Quackdoc said, `SetGPUThreadPriority` is possible. Currently, I'm asking for the `ID3D11Device` directly from ANGLE itself. However, this can be changed by this macro & afterwards create the Direct 3D device as you want with your required configuration: 

https://github.com/alexmercerind/media_kit/blob/083f128876f4a156a61c70a73c93558b808e3c1f/media_kit_core_video/windows/angle_surface_manager.cc#L26

https://github.com/alexmercerind/media_kit/blob/083f128876f4a156a61c70a73c93558b808e3c1f/media_kit_core_video/windows/angle_surface_manager.cc#L163-L190

<hr> 

On my machine, `package:media_kit` automatically selects `--hwdec` as `dxva2-copy`. Infact, mpv itself works smooth-est with `dxva2-copy` on my machine instead of the default mpv selects (without rendering API it selects some Direct3D `--hwdec`).

**Comment by alexmercerind** [comment]
FYI I have enabled GitHub actions & artifacts on the repository.
You can fork & make changes within browser to get a release build to test out.

See: https://github.com/alexmercerind/media_kit/actions/runs/3805543501 (scroll down for release build).

**Comment by Quackdoc** [comment]
I have been using the recent patch for a little bit now, it has **seemingly** mostly solved my issue at least when using the example app, I plan on testing more throughly tommorow, as I can dedicate a long time to testing it

**Comment by sudongg** [comment]
@alexmercerind
The swapinterval I said does not mean the opengl-swapinterval of mpv, the opengl-swapinterval setting of mpv seems to be valid only in mpv window mode. Need to set swapinterval (I use glfwSwapInterval) on opengl side.
Using glFinish or glfinish should just increase the possibility of flickering, at least in my project I use SwapBuffer (glfwSwapBuffers).

**Comment by sudongg** [comment]
The new exe doesn't flicker for me anymore, I can't test the Quackdoc issue, need more feedback from new users.

**Comment by alexmercerind** [comment]
> @alexmercerind The swapinterval I said does not mean the opengl-swapinterval of mpv, the opengl-swapinterval setting of mpv seems to be valid only in mpv window mode. 

Yeah! `opengl-swapinterval` is only valid for `--vo=opengl`, it has nothing to do with `--hwdec`.
Since, we're using ANGLE with Open GL ES 2.0, we have `eglSwapInterval`, which can be interesting to play around with.

Unfortunately, I'm not flickering either, so can't test.

<hr>

> Using glFinish or glfinish should just increase the possibility of flickering, at least in my project I use SwapBuffer (glfwSwapBuffers).

I feel the same. Unfortunately, even if I don't flush/finish/swap-buffer, the video content still gets drawn to screen.
I'm not sure what's swapping the back buffer. Even in current state, my worst fear will be to know that `glFinish` is not actually "syncing" but just adding a voluntary delay each frame which compensates for the flicker time. However, there's no way I can tell.

**Comment by alexmercerind** [comment]
Working on pre- Windows 10 devices as well (Windows 7 & 8.x) where DirectX 11 is supported.

Flutter itself uses software rendering when DirectX 11 is not supported (however texture doesn't work then).
Not a priority. Needs a fix in Flutter itself to use same fallback software rendering in texture API.

![0](https://user-images.githubusercontent.com/28951144/212839309-3d94bd2b-66ed-4318-b434-49e9fdf09b8c.PNG)
![1](https://user-images.githubusercontent.com/28951144/212839316-840bc0f1-1395-4dec-be6d-29f205984216.PNG)
