### ISSUE TITLE
[Question] Is custom configuration of `mpv.conf` available?

### ISSUE THREAD

**Issue by ragasubekti** [alexmercerind/media_kit#129]
Since in my understanding this project uses `libmpv` as the backend is it possible to support custom configuration of `mpv.conf`?

**Comment by alexmercerind** [comment]
This is a media playback library, not a media player. Let's have support for all platforms in 1.0.0 first.

The libmpv binaries that we're shipping are heavily stripped. Secondly, you can still implement a similar mechanism on your project.

**Comment by ragasubekti** [comment]
Thankyou!
Yes i understand that this is a library, i was wondering because the `PlayerConfiguration` is limited and that's answered my question.

**Comment by alexmercerind** [comment]
Not every feature from libmpv has been exposed in a common API, neither libmpv's exact API is kept, primarily becase:
- libmpv's behavior changes across versions, this could break the usage & make things confusing for developers.
- libmpv's API is substantially low-level as compared to `Player` class package:media_kit offers.
- libmpv is just one of the backends that project has right now (because it's the best). On other platforms e.g. web where libmpv can't be used (or we decide to switch to something else), the features that we would have exposed wouldn't work as expected (because they're exclusive to libmpv). So, only a fine number of features which can be implemented across platforms have been exposed as part of `Player` class.

However, you can still easily modify properties/options specific to libmpv with following API:

```dart
final player = Player();
if (player.platform is libmpvPlayer) {
  await (player.platform as dynamic).setProperty('terminal', 'yes');
  await (player.platform as dynamic).setProperty('msg-level', 'all=v');
}
```
