### ISSUE TITLE
Subtitles in m3u8 not recognized

### ISSUE THREAD

**Issue by postacik** [alexmercerind/media_kit#134]
I have a video file url (m3u8) which returns the following content:

```
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="Audio",NAME="MA_0_tr",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="tr"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="Audio",NAME="MA_1_eng",DEFAULT=NO,AUTOSELECT=NO,LANGUAGE="eng", URI="MA_1_eng/Stream.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="Subs",NAME="Turkish",DEFAULT=YES,AUTOSELECT=YES,FORCED=NO,LANGUAGE="tur",CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog, public.accessibility.describes-music-and-sound",URI="S_6_tur/Stream.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=2500000,CODECS="mp4a.40.2,avc1.4d4028",RESOLUTION=1920x1080,AUDIO="Audio",SUBTITLES="Subs"
MV_2500/Stream.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1500000,CODECS="mp4a.40.2,avc1.4d401f",RESOLUTION=1280x720,AUDIO="Audio",SUBTITLES="Subs"
MV_1500/Stream.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1000000,CODECS="mp4a.40.2,avc1.4d401f",RESOLUTION=960x540,AUDIO="Audio",SUBTITLES="Subs"
MV_1000/Stream.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=700000,CODECS="mp4a.40.2,avc1.4d401f",RESOLUTION=640x360,AUDIO="Audio",SUBTITLES="Subs"
MV700/Stream.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=96000,CODEC="mp4a.40.2",AUDIO="Audio",SUBTITLES="Subs"
MA_0_tr/Stream.m3u8
```

media_kit lists audio and video streams properly but does not recognize the subtitles. The only options for subtitles come out to be "auto" and "no".

When I try to play the same url with mpv, I get the following error:

`[ffmpeg/demuxer] hls: Can't support the subtitle(uri: S_6_tur/Stream.m3u8)
`

The subtitle can be shown properly with better_player on both Android and iOS.

I am sure this is not a media_kit but mpv issue but is there any workaround (maybe an option of mpv?) you know to overcome this problem?

**Comment by postacik** [comment]
I tried if I could download the subtitles using ffmpeg.

First I tried the following:

`ffmpeg -i "https://somesite/S_6_tur/Stream.m3u8" -c copy output.srt`

...and got the following error:

`[srt @ 0x13af05420] Unsupported subtitles codec: webvtt`

Then I replaced the `-c copy` option with `-scodec srt` as below:

`ffmpeg -i "https://somesite/S_6_tur/Stream.m3u8" -scodec srt output.srt`

...and it worked and downloaded the subtitles as srt file.

Can this be a clue to resolve this problem with an option of mpv?

**Comment by birros** [comment]
Can you specify on which platforms this problem happens?

**Comment by postacik** [comment]
I've tested only on MacOS but I can test it on Windows, too...

**Comment by birros** [comment]
The rendering of subtitles is done by libass on which mpv depends, this may be due to a missing configuration during compilation which is specific to each platform.

**Comment by postacik** [comment]
I get the same result for subtitles on Windows:

```
[log] Videos: (6) [VideoTrack(auto, null, null), VideoTrack(no, null, null), VideoTrack(1, null, null), VideoTrack(2, null, null), VideoTrack(3, null, null), VideoTrack(4, null, null)]
[log] Audios: (8) [AudioTrack(auto, null, null), AudioTrack(no, null, null), AudioTrack(1, null, eng), AudioTrack(2, null, tr), AudioTrack(3, null, tr), AudioTrack(4, null, tr), AudioTrack(5, null, tr), AudioTrack(6, null, tr)]
[log] Subtitles: (2) [SubtitleTrack(auto, null, null), SubtitleTrack(no, null, null)]
```

**Comment by birros** [comment]
> When I try to play the same url with mpv, I get the following error:
>
> [ffmpeg/demuxer] hls: Can't support the subtitle(uri: S_6_tur/Stream.m3u8) 
>
> The subtitle can be shown properly with better_player on both Android and iOS.
> 
> I am sure this is not a media_kit but mpv issue but is there any workaround (maybe an option of mpv?) you know to overcome this problem?

Ok, I missed your comment above, indeed it's specific to `mpv`, more specifically to `ffmpeg` as indicated in the logs.

Many errors exist about this problem on the `ffmpeg` tracker: https://trac.ffmpeg.org/search?q=m3u8+webvtt
I believe @solsticedhiver had the same issue. Maybe he found a solution or a workaround.

Knowing that the scope of what `media_kit` can do to solve this problem is limited, I decide to close this issue.
Feel free to discuss / add comments to share tips or if you find solutions… or open again if after researching, it's really up to `media_kit` to solve this issue…

**Comment by solsticedhiver** [comment]
I can elborate but this is complicated.
First, there is the issue [#10149](https://trac.ffmpeg.org/ticket/10149) of ffmpeg, where you end up with an error like:

    sidx reference_type 1 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
    If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)

This error comes from ffmpeg, but mpv too.

My work-around for that, is to parse the m3u8, to get the stream of video, audio, and subtitle. not the m3u8, but the mp4 streams or whatever.

Then specify, in ffmpeg, you can specify each sperate stream to be played with something like:

    ffmpeg -i $video -i $audio -i $subtitle -map 0:v -map 1:a -map 2:s -c:v copy -c:a copy -c:s mov_text $outputFilename

you can do the same with mpv and media_kit, the option are just different.

with media_kit, just specify a Media() for the video, and then add audio and subtitle with setProperty on player hanfler like:

```dart
final pp = player.platform as libmpvPlayer;
pp.setProperty('sub-files', subtitle);
pp.setProperty('audio-files', audio);
// and then
player.open(Playlist([Media(video)]));
```
WARNING: there is a trap there, because on some platform you need to escape ':' of url when passing the url to setProperty. on linux, mainly. look at [mpv man page about list](https://man.archlinux.org/man/mpv.1#String_list_and_path_list_options)

But there is a catch. Because of issue [#10169](https://trac.ffmpeg.org/ticket/10169) of ffmpeg, some webvtt are not processed correctly, because of the STYLE paragraph.

My work-around for that, is to download the webvtt, and remove the STYLE section, and pass a local webvtt file to media_kit, like shown above (but a local file instead of an url)

**Comment by postacik** [comment]
@solsticedhiver , thanks for the detailed explanation.

Downloading the subtitle and using `sub-files` property of mpv to load it externally is also my primary intention since webvtt is not processed correctly in my case.

I have two items to resolve to achieve this:

1) Parse m3u8 and get the URLs of available subtitle streams.
2) Download selected subtitle stream as srt file.

Which flutter package are you using to parse m3u8?

I can convert the subtitle stream to srt using ffmpeg with a command like below:

`ffmpeg -i "https://somesite/S_6_tur/Stream.m3u8" -scodec srt output.srt`

Or I can also download it as vtt:

`ffmpeg -i "https://somesite/S_6_tur/Stream.m3u8" -c copy output.vtt`

Have you done this with flutter, if yes, which package did you use?

**Comment by solsticedhiver** [comment]
I am doing it with [flutter_hls_parser](https://pub.dev/packages?q=flutter_hls_parser)

If you want all my code, it's there: https://github.com/solsticedhiver/flarte/blob/main/lib/downloader.dart
