### ISSUE TITLE
[Enhancement] Support lower macOS versions

### ISSUE THREAD

**Issue by theolundqvist** [alexmercerind/media_kit#160]
lowest supported macos version is 11.0 which corresponds to devices from 2013 and 2015 which is a little bit high for my target group. Is it possible to support lower versions or are there any technical limitations?

**Comment by birros** [comment]
When building macOS libs < 11.0, the Apple sdk forces a minimum version to 11.0 only for arm64. That's why I selected 11.0 as the minimum version for both archs…

But after reflection, it may be a bug in the Apple sdk, because there is also a bug when building the libs for the iOS arm64 simulator…

I'll try a little hack, a similar method as the one used to fix the simulator libs, by "forcing" the minimal version of the libs produced for Apple Silicon to a lower version.

⚠️  **However, just to be clear, I will try it, but I can't guarantee that the libs will be stable for a version < 11.0.**
