### ISSUE TITLE
[Enhancement] state stream

### ISSUE THREAD

**Issue by clragon** [alexmercerind/media_kit#170]
In the demo, we can see this fun construct: 
[SeekBar](https://github.com/alexmercerind/media_kit/blob/main/media_kit_test/lib/common/widgets.dart#L147)
Where we have to listen to many different streams at once.
This is a bit inconvenient. Would it perhaps be possible to expose a single stream that holds the entire `state` of a player?
I think that would probably help for quite a few cases where we need access to multiple properties at once.

**Comment by alexmercerind** [comment]
Hi!

I don't think I'm in favor of this. Primarily due to two reasons:

1. It's genuinely inefficient. A single `Stream` which publishes updates to all the events will trigger re-draws _very-very_ often. The position `Stream` itself updates more over 10-ish times per second & mixing that with other events will be too much. As time goes on, I'm sure we're going to have more events exposed e.g. #166.
  A good argument to this can be, "people can still subscribe to specific event's `Stream`, when they want.". My response to this will be that, it promotes a practice I can't recommend. It will also become easy for users to abuse it. Also: they still can!
2. From library standpoint, having a separate `Stream` for each event is good & preferred. In application's code (which depends on package:media_kit), I'd recommend one to maintain state of their "media playback instance" inside separate class (which is a `ChangeNotifier`, `StateNotifier`, `Bloc` or `Cubit`; and has a `Player` object in it). Make subscriptions & expose attributes as required there.

**Other:**

I spent a lot of time on API design of this library. _Polluting_ the `Player` class directly with state attributes didn't feel right (and it feels even more right as time has went), so I added `PlayerState` & `PlayerStreams` objects in composition with the parent `Player` instance. This very elegantly separates the event properties from methods of the class. Having a separate `Stream` for each event is good & preferred.
In my quest of making the perfect media library, I made dart_vlc (side-project quality code) before this. Few events were merged into single `object` to which many people genuinely raised concerns after facing frequent redundant re-draws.

**Comment by clragon** [comment]
I see. In that case I will close this issue.
I was about to make an extension for myself but I noticed that the PlayerState class is not exported. That might be worth a consideration at least. I suppose I will go and manually zip my streams... Records will make this less painful eventually.
