### ISSUE TITLE
[Bug Report] Multiple Windows created when creating multiple Video

### ISSUE THREAD

**Issue by bdlukaa** [alexmercerind/media_kit#21]
**The problem**
I tried adding multiple `Video` widgets to the view using a grid view, but multiple windows were created

**Screenshots**
The bug:
![image](https://user-images.githubusercontent.com/45696119/212579672-7f9f354b-1d25-4cee-9c84-f42cf386ca22.png)
![image](https://user-images.githubusercontent.com/45696119/212579690-25a65e29-6d13-4dea-a524-be2c43168745.png)

The desired behavior:
![image](https://user-images.githubusercontent.com/45696119/212580223-5a1eb9fe-7783-4fcc-9f66-942db72b6e54.png)

**Additional context**

https://github.com/bluecherrydvr/unity/tree/main/packages/unity_video_player/unity_video_player_media_kit

**Comment by alexmercerind** [comment]
From the expected API usage (that I've planned).

The `Future` from `VideoController.create` should be completed/resolved before `Player.open`. If not, a separate window will spawn. If the new window is still spawning, something could be wrong in my implementation.

<hr>

My recommendations on your code:


### Problem

[This seems to be causing the race](https://github.com/bluecherrydvr/unity/blob/44522c55e314e52ccc74faa3199817892a3fe41d/packages/unity_video_player/unity_video_player_media_kit/lib/unity_video_player_media_kit.dart#L71-L83). You are likely invoking [`UnityVideoPlayerMediaKit.setDataSource`](https://github.com/bluecherrydvr/unity/blob/44522c55e314e52ccc74faa3199817892a3fe41d/packages/unity_video_player/unity_video_player_media_kit/lib/unity_video_player_media_kit.dart#L147) before [`_MKVideo`](https://github.com/bluecherrydvr/unity/blob/44522c55e314e52ccc74faa3199817892a3fe41d/packages/unity_video_player/unity_video_player_media_kit/lib/unity_video_player_media_kit.dart#L54) gets mounted (_i.e._ [this gets called](https://github.com/bluecherrydvr/unity/blob/44522c55e314e52ccc74faa3199817892a3fe41d/packages/unity_video_player/unity_video_player_media_kit/lib/unity_video_player_media_kit.dart#L78-L81)).

### Solution

It will be a good idea to move `VideoController` into [`UnityVideoPlayerMediaKit`](https://github.com/bluecherrydvr/unity/blob/44522c55e314e52ccc74faa3199817892a3fe41d/packages/unity_video_player/unity_video_player_media_kit/lib/unity_video_player_media_kit.dart#L108). Primarily because you DON'T NEED multiple `VideoController`s for each `Video` widget (same will work). Infact, if you call `VideoController.create` multiple times for same `Player`, native code will return "same controller" internally.

What you can do ideally is to keep a `Completer<VideoController>` which gets resolved & you can remove the race condition by accessing `VideoController` using `completer.future`.

<hr>

Please feel free to follow up.
You can try the example application testing multiple possible situations from GitHub Action artifacts.

**Comment by bdlukaa** [comment]
Thanks, it works! I believe this can be closed
