### ISSUE TITLE
Obtaining aspect ratio of video

### ISSUE THREAD

**Issue by pmjobin** [alexmercerind/media_kit#212]
Hello,

I've been trying to find the appropriate method to compute the aspect ratio of videos. It appears as though the width & height members of PlayerState are not initialized immediately after calling Player.open() . I also attempted to access these members by registering a callback on the "playing" event of the stream but width & height do not appear to be initialized by that point either. One strange phenomenon I observed is that if I open a second video (and a third and so on), the width & height members will be set to the values from the previous video.  This can be easily verified by changing the line...

`player.open(Media(sources[i]));`

... to...

`player.open(Media(sources[i])).then((e) => print("*** width = ${player.state.width}, height = ${player.state.height} ***"));`

... in the 01.single_player_single_video.dart example code and then, alternating between the first and second videos in the list. The printed out width & height values are always that of the previously selected video.

Thank you,
P-M

**Comment by alexmercerind** [comment]
Hi!

At current stage, we aren't really aiming to dive into the deeper things as such. The package's goal is to play videos & audios; that in a stable & performant manner across platforms.

If you look at official [`package:video_player`](https://pub.dev/packages/video_player), it doesn't even provide so many features & properties. The goal you're trying to accomplish is related to metadata parsing; which is entirely different from playback.

With that being said, you still have options & it happens to be possible with media_kit:

1. Use `player.state.*` instead of `player.streams.*`. It will notify you when `width`/`height` changes.
2. Use `VideoController.waitUntilFirstFrameRendered` to wait until first video frame is drawn.
3. Use `VideoController.rect` to get notified about video resolution.

**Comment by pmjobin** [comment]
Method 3 works perfectly for me. Thanks!
