### ISSUE TITLE
Current status of project (Question)

### ISSUE THREAD

**Issue by sommye-ctr** [alexmercerind/media_kit#226]
Thanks for the awesome project and it looks really promising. I see the 1.0 roadmap and the active work being done in the project. Just wanted to ask if the project can be (or suggested to) used in an app or is it still in a "beta" stage.

Again, thanks for all the work.

**Comment by alexmercerind** [comment]
Hi @sommye-ctr,

Yes, you may use [package:media_kit](https://pub.dev/packages/media_kit) in your projects without any hesitation. There are already many apps using it.

We have direct demo links for each platforms in the README, which you may try. You will experience good stability & performance on every platform. Other than that, project is also well tested.

The 3 reasons due to which [package:media_kit](https://pub.dev/packages/media_kit) is not 1.0.0 yet are:
- One or more goals are left.
- By having a version 0.0.x, it allows to not adhere to [semantic versioning](https://dart.dev/tools/pub/versioning#semantic-versions) while project is in development.
- A bit more peace for me (during development) I guess. Once I feel ready for 1.0.0, I would publicize things that way.

<hr>

Hopefully, I will be able to work a lot (lot) faster after 15th of this month. Expect a 1.0.0 by the end of this month.

Regardless, what's already been done is quite stable & performant for usage. And... everything is open to feedback.

**Comment by alexmercerind** [comment]
I have my semester exams till 15th; unable to sprint here.

**Comment by sommye-ctr** [comment]
That's great, thanks for the quick reply. Also, does the library support caching of videos during the progress or between app sessions?
