### ISSUE TITLE
How to catch video error

### ISSUE THREAD

**Issue by waulite-786** [alexmercerind/media_kit#289]
player.stream.error.listen(
      (String event) {
      Print.log(tag: "error...................... 1->", message: '$event');
    });

it is not listing how can we track video playing error

**Comment by waulite-786** [comment]
first i want to start play video then set ui but i am geting this log 
PlayerLog(prefix: vo/libmpv, level: fatal, text: No render context set.)

**Comment by hitesh-yoboshu** [comment]
Have you tried downloading the demo or trying out sample code given in README?

**Comment by waulite-786** [comment]
yes, it is working fine I tested it but my requirement. is I am plying image video, but when I load page in desktop for a while? showing blank I want to update Ui when video start playing? or please tell me any way to get video thumbnail from path in flutter desktop. library is available for thumbnail. only android and IOS but not window

**Comment by alexmercerind** [comment]
I can't help or provide consultancy; please be clear. I don't have much time.

The README has good documentation & the example application demonstrates everything very well.

<hr>

Regardless, if you are playing videos served from your backend; DO NOT EXTRACT the thumbnail from it (serve them separately). All websites & services e.g. YouTube, Instagram etc. serve video thumbnails separately & display them before video stream is ready. **If it was easy to extract a thumbnail from a video, one would play the video directly instead of having a thumbnail.**

**Comment by alexmercerind** [comment]
You can catch errors as intended (if any condition is missing, please let us know). Your last statement changed to something else... What do I understand from it? You can quite easily play around with code we have provided in our demo application.

**Comment by alexmercerind** [comment]
Also: #39
