### ISSUE TITLE
[BUG] V/A out of sync when increasing `Player.rate`

### ISSUE THREAD

**Issue by birros** [alexmercerind/media_kit#45]
While working on the implementation for macOS, I noticed that there was a progressive audio and video desynchronization when I change the rate of the Player:

```dart
player.rate = 2.0;
```

## Tests (commit 21eb88d)

| Platform | Behavior         |
| -------- | ---------------- |
| macOS    | V/A out of sync  |
| Linux    | V/A out of sync  |
| Windows  | Not tested       |

## Ideas

One of these three possibilities may explain it:

- If the issue is not present on Windows, it's possible that the lack of thread usage in the Linux and macOS implementations could be causing it
- A missing option may be required by mpv
- A bad implementation of rendering, perhaps certain frames need to be manually dropped, maybe through `MPV_RENDER_PARAM_SKIP_RENDERING`

**Comment by alexmercerind** [comment]
This is actually possible. Current rate/pitch implementation was made to cater demands of my own project & heavily relies on scaletempo filter. We need to use the default rate API in libmpv.

**Comment by birros** [comment]
Ok, I found the problem, it's a mistake on my part, I confused the `Player.rate` property, which is specific to **media_kit** with `libvlc_media_player_set_rate` which I use in my **VLC** based project.

The equivalent of `VLCMediaPlayer.rate` for **mpv** would be `Player.speed`, in C it looks like this:

```c
gdouble speed = 2.0;
mpv_set_property(mpv, "speed", MPV_FORMAT_DOUBLE, &speed);
```

To control the `speed` with the current **media_kit** API we need to do this:

```dart
if (player.platform is libmpvPlayer) {
  (player.platform as libmpvPlayer?)?.setProperty("speed", "2");
}
```

Can I submit a pull request to add `Player.speed`?

**Comment by alexmercerind** [comment]
I'm welcomed to PR btw!

**Comment by birros** [comment]
I did see the comment in the code.

I hope not to offend, but I think this "hack" is more appropriate in **Harmonoid** than here, as it is specific to its logic, **media_kit** has more to gain by being "agnostic" about the apps that use it.

Also, I think it is important to avoid changing properties only in the configuration passed to the player. Its behaviour / properties should also be accessible / changeable on the fly, to give developers more flexibility.

Better safe than sorry!

If you think it's still relevant to leave this "hack" in **media_kit**, I suggest you use a getter / setter (eg: `bool audioPitchCorrection`, also in configuration, to be able to modify the audio pitch correction on the fly. And expose the other upstream properties of **mpv** next to it.

**Comment by alexmercerind** [comment]
First off (just to clarify in advance):

Yes, I believe this is indeed an issue & I will fix it so that the `rate` setter works with the video rendering implementation I made. I'm fully committed to make everything work correctly & give a stable experience to all future dependents of `package:media_kit`.

I understand that it means to provide a neutral API to everyone & for exact same reason, I have decided to architecture the project such way. `PlatformPlayer` defines a set of minimal platform independent APIs which I plan to implement for all platforms:

https://github.com/alexmercerind/media_kit/blob/21eb88d28f555866f18d1db09f2ebd79f1248487/media_kit/lib/src/platform_player.dart#L80-L172

Since, not every feature can be implemented for each platform or available in every backend. For instance, `audio-pitch-correction` itself cannot be changed on fly in libVLC (unlike libmpv). On the other hand, pitch/rate behaviour is entirely different on ExoPlayer & works out of box.

package:media_kit is not tied to libmpv only (God knows what backend I have to use on Android/iOS) & I believe this property is very "specialized" & thus something which cannot be offered in a common API.

<hr>

An average user of the package:media_kit won't even know what's libmpv or what's libVLC etc. or their specifics. They just want a complete API that works fine for the most part.

`PlatformPlayer`, I believe defines sufficient APIs for it. Offering this common "agnostic" API should be:
- High-level enough for easier usage _e.g. you can see most streams & events I implemented don't exist inherently in libmpv._
- As less platform specific as possible to avoid any confusions etc.
- Works well for both audio & video users.

Obviously, if a user wants to dive-in deep:
- They can use the `setProperty` API which I made public for libmpv backend.
- They can customize the initialization parameters through `PlayerConfiguration`.

TBH even `pitch` setter is kind of "over-kill" & I'm fine with removing it completely OR hiding that behind a `PlayerConfiguration` flag (like I recommended earlier).

**Comment by alexmercerind** [comment]
Hi!

Latest commit at fb08412c970de8e77eb835d6551008b506177f84 should resolve it.

Thanks!
