### ISSUE TITLE
[Question] GPU not used fully (<100%) on Windows

### ISSUE THREAD

**Issue by damywise** [alexmercerind/media_kit#48]
GPU is capped at ~30% on stress test and the videos are skipping frames. Is that intentional?

**Comment by alexmercerind** [comment]
How's the CPU usage?

**Comment by alexmercerind** [comment]
So... I just wanted to answer this real quick.

First off, I as human being can't deal with computational limitations or how science, CPUs or GPUs etc. work. I'm pretty sure if we launch 20 simultaneous instances of any video player, all of them will start dropping the frames.

The load on my integrated GPU goes as high as 95% on that stress test screen of the test application. Lastly, that last stress test screen isn't really how one should use this library or attempt to break the limits etc. It's simply a test that aims to check whether there are any possible race conditions or memory leaks etc.

If I had to render 20 videos simultaneously in production, the first thing I would do is pass fixed width & height to VideoController.create. Because by default, all Video widgets use texture size as video resolution, which means we are sort of rendering 20 physical monitors (!!!). Here, manually specifying the texture size will allow us to limit the total size of textures less than equal to the current monitor.

Still, you are free to compare performance of package:media_kit with a window of Google Chrome rendering 20 <video> elements simultaneously. 

Why did I ask CPU usage above? Because only rendering is done on GPU, but the frame event is still notified by CPU. Running 20 separate threads, each notifying a draw is also kind of expensive. Also, there is additional cost of notifying events to Dart VM from C/C++, you can disable this as well.

Read: https://github.com/alexmercerind/media_kit#performance

**Comment by alexmercerind** [comment]
There is still a scope of performance improvement & that is removing ANGLE completely & using Direct3D directly between libmpv & Flutter without any interop. This will also allow libmpv to work without any `*-copy` hwdec.

This can only happen when libmpv offers a D3D render API (instead of current GL one): https://github.com/mpv-player/mpv/issues/5979.
Current performance is already very-very good (and in some cases `*-copy` hwdec are actually more performant) & what I linked above is over-kill for now. I don't have time or funds to work on that.
