### ISSUE TITLE
[Enhancement] Android support

### ISSUE THREAD

**Issue by shithappens2016** [alexmercerind/media_kit#57]
**Edit by @alexmercerind:**

Using this issue ticket / thread for dealing with Android support.

<hr>

**Original comment:**

We know that Android hardware video decoding (`mediacodec`) is deeply tied to the surface of android. And FFmpeg wraps `mediacodec` and can render directly to android surface. libmpv wraps FFmpeg again. Would you talk about the most efficient way for flutter to call libmpv on android for hardware decoding and rendering to flutter texture ?

**Comment by alexmercerind** [comment]
I believe this is a question.

Without diving much into the internal specifics of either libmpv or Android, there's a OpenGL render API from libmpv which I aim to use on Android like other platforms that I've implemented. It is fairly performant. [mpv-android](https://github.com/mpv-android/mpv-android) is a good reference application. I'm not really worrying about "wrapper"s, as long as the video output is hardware accelerated & capable of handling multiple 4K/8K videos at once. A `*-copy` `hwdec` does not indicate a "wrapper" but copy back to CPU RAM during render (may be anything, pixel buffer or any other video output related object). Flutter's own rendering mechanism & [`Texture`](https://api.flutter.dev/flutter/widgets/Texture-class.html) widget in itself is a wrapper & there is a high degree of inter-op involved on every platform it runs on.
[`TextureRegistry`](https://api.flutter.dev/javadoc/io/flutter/view/TextureRegistry.html) on Android seems to be based on Android's [`SurfaceTexture`](https://developer.android.com/reference/android/graphics/SurfaceTexture.html?is-external=true) which AFAIK is GL backed.

Even for Windows, as you can see in the video attached in `README.md` that _it still uses slight CPU_. Ideally, even that could be made absolute zero, if [we're able to remove current ANGLE translation layer](https://github.com/mpv-player/mpv/issues/5979). On the other hand, [`package:media_kit`](https://github.com/alexmercerind/media_kit) is already more performant than a `<video>` in [Google Chrome](https://en.wikipedia.org/wiki/Google_Chrome) or [Media Player, shipped with Windows 11](https://en.wikipedia.org/wiki/Media_Player_(Windows_11)).

Like everything in computer science, "Pre-mature optimization is the root of all evil.".
From that standpoint, we're fairly satisfied with the order of performance. Secondly, if any of our customer is specifically aiming for highest order of performance possible, then they shouldn't possibly use Flutter in the first place. With that being said, I'm also looking forward to any improvements that can be made.

Coming back to Android, first step to all this will be to having an implementation in the first place.  Currently, it's uncertain if we should use keep using libmpv like other platforms or use [ExoPlayer](https://github.com/google/ExoPlayer) instead. There are trade-offs with everything, bundle size (fairly important for mobile applications), performance & licensing etc. Few projects I know look for a solution to render RTSP streams on Flutter Android & unfortunately it's something ExoPlayer can't. In such a case, libmpv based backend will be really good.

**Comment by alexmercerind** [comment]
Just to clarify, I personally do believe that Flutter is really performant & best choice for making applications of any kind.

**Comment by shithappens2016** [comment]
Thanks for sharing your views, very inspiring.  I would also like to discuss some details with you.
I've briefly looked at the code for mpv-android. It simply takes the android surface and gives it to libmpv.
https://github.com/mpv-android/mpv-android/blob/master/app/src/main/jni/render.cpp#L15-L19
We know that  mediacodec is tied to android‘s surface. without android‘s surface you can't even start mediacodec.
If so, flutter's PlatformView will be inevitable.

**Comment by alexmercerind** [comment]
Thanks for taking a look. I haven't done much detailed analysis of the Android yet.

However, I'm pretty sure there are similar challenges for each platform, like I faced on Windows. Current implementation also seemed impossible few months ago because API from libmpv is OpenGL based, while the H/W based texture API in Flutter Windows is DirectX 11 based. Design document, package architecture, FFI, platform channels, hosting ANGLE, translation layer, texture support, black flickers etc. etc. There's a lot that I had to do to get it working.

<hr>

> I've briefly looked at the code of mpv-android. It simply takes the android surface and gives it to libmpv.

Oh... That's interesting. So, it uses `--wid` on Android for rendering. I thought there was hardcore OpenGL ES usage (like we have) on Java/Kotlin side of things. AFAIK, there should still be two types of rendering possible:

1. `--vo=gpu`: Allowing us to use OpenGL ES & render into a [`SurfaceTexture`](https://developer.android.com/reference/android/graphics/SurfaceTexture.html?is-external=true), which then Flutter can consume.
2. `--vo=mediacodec_embed`: The one that renders directly into [`android.view.Surface`](https://developer.android.com/reference/android/view/Surface) & I believe mpv-android uses.

This comment further specifies things:

https://mpv.io/manual/stable/#video-output-drivers-mediacodec-embed

<hr>

> If so, Flutter's platform view will be inevitable.

That's quite certainly true. It's the only way to get native Android components like [`android.view.Surface`](https://developer.android.com/reference/android/view/Surface) shown in Flutter. I'll try my best to avoid platform view usage at all costs. I feel it's not good from performance standpoint & has many other trade-offs.

<hr>

Now that you've told me that `--wid` works on Android, my goal will be to try & get it working first. IMO it's conceptually very clean API for hosting. It will save me from getting my hands dirty with Java/Kotlin & other platform specific GL issues etc.

It seems that this should be possible as well (AFAIK), [`android.view.Surface`](https://developer.android.com/reference/android/view/Surface) has a [constructor that takes `SurfaceTexture`](https://developer.android.com/reference/android/view/Surface#Surface(android.graphics.SurfaceTexture)) & [`SurfaceTexture`](https://developer.android.com/reference/android/graphics/SurfaceTexture.html?is-external=true) is something Flutter can easily read from. As long as... it can work "off-screen".

If `--wid` does not work, I will bother with `--vo=gpu` etc. & go down that road (hoping that'd work).

**Comment by alexmercerind** [comment]
I've re-opened this issue for targeting Android issue. Why keep it all just a discussion :)

I'm assigning myself for now, however I'm kind of busy these days. I'd love to work on supporting Android.

**Comment by alexmercerind** [comment]
I made initial implementation. Try out APK: https://drive.google.com/file/d/1nqqNGqoUt6oXM1DJ4g7kWCmr5FUzOMUy

Even though this may look ready, there's a large scope of work required before landing #100.

**Comment by alexmercerind** [comment]
Don't try the stress test for now.
