### ISSUE TITLE
[Bug Report] native_event_loop: Hot restart interrupts the listening of events

### ISSUE THREAD

**Issue by birros** [alexmercerind/media_kit#74]
This is a minor bug, as it does not affect an app in production, only in development.

When the `native_event_loop` is used, if we hot restart the app in dev mode the mpv events are no longer listened by the `Player`.

**Comment by alexmercerind** [comment]
Is it really happening?
Once hot restart takes place, a different instance of `Player` with different `mpv_handle*` should be created.
So, new event loop should be registered for it.

<hr>

Ideally, I'd like to clear all `Player` instances upon a hot-restart, but since our whole implementation is completely in Dart, it's going to be a bit challenging. Maybe, we can request users to call some initialization method before `runApp`, where we can internally clear existing resources & event threads.

**Comment by alexmercerind** [comment]
Shouldn't this be happening even without native event loop?

<hr>

Eitherway, maybe we can dedicate native event loop to dispose tasks upon hot-restart.
Is there any way to listen to application lifecycle?

https://github.com/flutter/flutter/issues/10437

**Comment by alexmercerind** [comment]
And it's working before hot-restart?

**Comment by birros** [comment]
Yep

**Comment by birros** [comment]
Ok, I think I found where the bug comes from: [media_kit_native_event_loop/src/media_kit_native_event_loop.cc#L21-L27](https://github.com/alexmercerind/media_kit/blob/e2fe0a25cb132456c1b6ed6bbfbee0c5ad4ce182/media_kit_native_event_loop/src/media_kit_native_event_loop.cc#L21-L27)

When I skip the conditions, the events are sent after the hot restart.

```c++
// if (post_c_object_ == nullptr) {
  post_c_object_ =
      reinterpret_cast<bool (*)(Dart_Port, Dart_CObject*)>(post_c_object);
// }
// if (send_port_ == -1) {
  send_port_ = send_port;
// }
```

**Comment by alexmercerind** [comment]
👏👏👏 May you please raise a PR.
AFAIK only removing send port should also work. I'm surprised how it kept working on Windows & Linux.
