### ISSUE TITLE
[Bug Report] Can't release app on the iOS App Store

### ISSUE THREAD

**Issue by JulienDev** [alexmercerind/media_kit#93]
Hello,

I've integrated media_kit in an iOS app and when I upload the binary to the iOS App Store, I receive an email saying that my app has an issue : 

> ITMS-90429: Invalid Swift Support - The files libswiftDarwin.dylib, libswiftMetal.dylib, libswiftCoreAudio.dylib, libswiftsimd.dylib, libswiftQuartzCore.dylib, libswift_Concurrency.dylib, libswiftos.dylib, libswiftObjectiveC.dylib, libswiftDispatch.dylib, libswiftCoreGraphics.dylib, libswiftCoreData.dylib, libswiftCoreFoundation.dylib, libswiftUIKit.dylib, libswiftCoreMedia.dylib, libswiftAVFoundation.dylib, libswiftCore.dylib, libswiftFoundation.dylib, libswiftMediaPlayer.dylib, libswiftCoreImage.dylib aren’t at the expected location /Payload/Runner.app/Frameworks. Move the file to the expected location, rebuild your app using the current public (GM) version of Xcode, and resubmit it.

I tried some workarounds I found on StackOverflow like:
- Set "Always Embed Swift Standard Libraries = YES"
- Set "Strip Siwft Symbols = NO"
But I always get the same error message from ASC

Do you know how I can fix it?

**Comment by birros** [comment]
I would like to specify (as I told to @JulienDev on Discord) that I have no experience of publishing apps on the App Store. If anyone has any ideas, they are welcome.

Also, there is no problem to build an iOS app in ipa format and install it with AltStore. Only when publishing on the App Store.

We don't know yet whether the resolution of this issue is the responsibility of the app developer or media_kit.

**Comment by birros** [comment]
I'm posting here what I've found since the discussion with @HankG on Discord about build problems for the simulator.
I think the two problems are related, using a `.xcframework` should fix both problems.

---

From the [Apple doc](https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-TROUBLESHOOTING-BUNDLE_ERRORS):

> Dynamic libraries outside of a framework bundle, which typically have the file extension .dylib, are not supported on iOS, watchOS, or tvOS, except for the system Swift libraries provided by Xcode.

I also inspected the structure that the MobileVLCKit cocoapod follows, it embeds a single dynamic lib for each arch / platform. Except that the current build of libmpv creates several dylib, I think it is possible to create as many frameworks as there are dylib, to check:

```
MobileVLCKit.xcframework
├── Info.plist
├── ios-arm64_armv7
│   ├── MobileVLCKit.framework
│   │   ├── Headers
│   │   │   ├── MobileVLCKit.h
│   │   │   ├── …
│   │   ├── Info.plist
│   │   ├── MobileVLCKit                     # dylib
│   │   ├── Modules
│   │   │   └── module.modulemap
│   │   └── PrivateHeaders
│   │       ├── VLCCustomDialogProvider.h
│   │       ├── …
│   └── dSYMs
│       └── MobileVLCKit.framework.dSYM
│           └── Contents
│               ├── Info.plist
│               └── Resources
│                   └── DWARF
│                       └── MobileVLCKit
└── ios-arm64_x86_64-simulator
    ├── MobileVLCKit.framework
    │   ├── Headers
    │   │   ├── MobileVLCKit.h
    │   │   ├── …
    │   ├── Info.plist
    │   ├── MobileVLCKit                     # dylib
    │   ├── Modules
    │   │   └── module.modulemap
    │   ├── PrivateHeaders
    │   │   ├── VLCCustomDialogProvider.h
    │   │   ├── …
    └── dSYMs
        └── MobileVLCKit.framework.dSYM
            └── Contents
                ├── Info.plist
                └── Resources
                    └── DWARF
                        └── MobileVLCKit
```

I think only dylib, folders and Info.plist are required.

The following command may be useful to create the `.xcframework`:
```shell
$ xcodebuild -create-xcframework \
    -framework /path/to/MPV.framework \
    -framework /path/to/SSL.framework \
    -output /path/to/MPV.xcframework
```
